version: '3.8'

services:
  web:
    build: .
    command: gunicorn documentation_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always
