# Generated by Django 5.0.9 on 2024-09-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_contentpage_delete_documentationpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentPage',
            new_name='DocumentationPage',
        ),
    ]
