# Generated by Django 5.0.9 on 2024-09-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0013_alter_documentationpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpage',
            name='heading_texts',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
