# Generated by Django 5.0.9 on 2024-09-17 01:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0014_documentationpage_heading_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('code', 4), ('heading', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', 'Heading 1'), ('2', 'Heading 2'), ('3', 'Heading 3')]}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('level', 5), ('text', 6)]], {})}),
        ),
    ]
