# Generated by Django 5.0.9 on 2024-09-18 06:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0017_documentationpage_word_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('code', 4), ('heading', 7), ('list', 8), ('table', 12), ('tree', 26)], blank=True, block_lookup={0: ('documentation.models.ParagraphBlock', (), {}), 1: ('documentation.models.ImageBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', 'Heading 1'), ('2', 'Heading 2'), ('3', 'Heading 3')]}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('level', 5), ('text', 6)]], {}), 8: ('documentation.models.ListBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (6,), {'label': 'Headers'}), 10: ('wagtail.blocks.ListBlock', (6,), {'label': 'Row'}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Rows'}), 12: ('wagtail.blocks.StructBlock', [[('headers', 9), ('rows', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 15: ('documentation.models.ImageBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('child_img', 15), ('content', 14)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14), ('child_img', 15), ('child', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14), ('child_img', 15), ('child', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14), ('child_img', 15), ('child', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14), ('child_img', 15), ('child', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'required': False}), 26: ('wagtail.blocks.StructBlock', [[('children', 25)]], {})}),
        ),
    ]
