# Generated by Django 5.0.9 on 2024-09-19 01:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0020_alter_documentationpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('code', 4), ('heading', 7), ('list', 8), ('table', 13), ('tree', 27)], blank=True, block_lookup={0: ('documentation.models.ParagraphBlock', (), {}), 1: ('documentation.models.ImageBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript')], 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', 'Heading 1'), ('2', 'Heading 2'), ('3', 'Heading 3')]}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('level', 5), ('text', 6)]], {}), 8: ('documentation.models.ListBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Headers'}), 11: ('wagtail.blocks.ListBlock', (6,), {'label': 'Row', 'required': False}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Rows', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('headers', 10), ('rows', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 16: ('documentation.models.ImageBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 14), ('child_img', 16), ('content', 15)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15), ('child_img', 16), ('child', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15), ('child_img', 16), ('child', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15), ('child_img', 16), ('child', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15), ('child_img', 16), ('child', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'required': False}), 27: ('wagtail.blocks.StructBlock', [[('children', 26)]], {})}),
        ),
    ]
