# Generated by Django 5.0.9 on 2024-09-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_documentationpage_homepage_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentationPage',
        ),
    ]
